version: '3'

services:
    app:
        container_name: 'docker-workshop-api'
        image: node:10.16.3-jessie
        restart: always
        command: /bin/bash -c "yarn; yarn start;"
        volumes:
            - ../api:/usr/src/app
        working_dir: /usr/src/app
        ports:
            - 4001:4000
        expose:
            - 4000
        networks:
            docker-workshop-network:

networks:
  docker-workshop-network:
    external: true