version: '3'

services:
    storage:
        container_name: 'docker-workshop-storage'
        image: mariadb:10.4.4-bionic
        restart: on-failure
        environment:
            MYSQL_DATABASE: workshop
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 33006:3306
        expose:
            - 3306
        command:
            [
                'mysqld',
                '--character-set-server=utf8mb4',
                '--collation-server=utf8mb4_unicode_ci'
            ]
        volumes:
            - ../database:/usr/src/database
        working_dir: /usr/src/database
        networks:
          docker-workshop-network:

networks:
  docker-workshop-network:
    external: true